#set page(paper: "us-letter", margin: 0.5in)
#set text(font: "Helvetica Neue", size: 8pt)

#align(center)[
  #text(size: 16pt, weight: "bold")[Morning Intel Report]
  #v(0.1em)  
  #text(size: 10pt)[January 29, 2026 - 123 Bookmarks via Bird CLI]
]

#line(length: 100%, stroke: 0.5pt)

= TL;DR
- Karpathy: 80 percent agent coding now
- Kimi K2.5: Open-source visual agent  
- ElevenLabs disrupted by open-source TTS
- OpenAI adding ads to ChatGPT
- Dario Amodei: AI risks essay

= All 123 Bookmarks

#table(
  columns: (auto, auto, auto, 1fr),
  inset: 3pt,
  fill: (col, row) => if row == 0 { rgb("#333") } else if calc.rem(row, 2) == 0 { rgb("#f8f8f8") } else { white },
  text(fill: white, weight: "bold", size: 7pt)[No],
  text(fill: white, weight: "bold", size: 7pt)[Author],
  text(fill: white, weight: "bold", size: 7pt)[Likes],
  text(fill: white, weight: "bold", size: 7pt)[Content],
  [1], [karpathy], [36,838], [A few random notes from claude coding quite a bit last few weeks.  Cod],
  [2], [Kimi Moonsho], [15,431], [🥝 Meet Kimi K2.5, Open-Source Visual Agentic Intelligence.  🔹 Global S],
  [3], [geerlingguy], [13,805], [ElevenLabs just got nuked by open source https://t.co/Ol6jVLTaCP],
  [4], [DarioAmodei], [13,634], [The Adolescence of Technology: an essay on the risks posed by powerful],
  [5], [thedulab], [11,255], [If you're aware that the term permanent underclass  even exists then i],
  [6], [OpenAI], [9,813], [In the coming weeks, we plan to start testing ads in ChatGPT free and],
  [7], [HuggingModel], [9,685], [NVIDIA just dropped PersonaPlex-7B 🤯  A full-duplex voice model that l],
  [8], [0xkyle], [9,267], [Reading what the CEO of Anthropic wrote, it is more clear than ever yo],
  [9], [ErnestoSOFTW], [8,722], [https://t.co/ytGkQRv5FC],
  [10], [thedankoe], [7,531], [https://t.co/2b9xu8HBXY],
  [11], [brave], [7,346], [Clawdbot, a 24/7 open-source AI assistant that actually does work, see],
  [12], [basedanarki], [7,199], [potential customers: “hey can you get back to us?”  the shit me and cl],
  [13], [felixprehn], [6,347], [The smartest people in the world are selling their companies at the ex],
  [14], [Kimi Moonsho], [6,125], [Kimi K2.5 has arrived! 🥝 Here are 2 things to know: Aesthetic Coding x],
  [15], [aakashgupta], [5,909], [Buried in 15,000 words of “here are the risks,” Anthropic’s CEO made t],
  [16], [gregisenberg], [5,760], [you probably can make 10m+ in 2026 by installing, configuring and opti],
  [17], [phokarlsson], [5,069], [It seems a common experience in the lives of people with high agency i],
  [18], [jiayuan jy], [5,062], [I let Claude Code turn karpathy's post into agent skills. It first gen],
  [19], [aisearchio], [4,365], [RIP Elevenlabs. Alibaba Qwen dropped this new AI text to speech  Free],
  [20], [mvanhorn], [4,358], [Just shipped /last30days. A Claude Code skill for claudeai that scans],
  [21], [ethanrow ai], [3,764], [Two great engineers quietly break down the mindset shift required to s],
  [22], [ralliesai], [3,644], [CLAUDE IS DESTROYING THE SP 500  Claude is not only good at coding but],
  [23], [nicbstme], [3,578], [https://t.co/KT2QfXnFad],
  [24], [ericw ai], [3,573], [Instead of watching a 2-hour movie, read this masterclass on how to be],
  [25], [NetworkChuck], [3,287], [My server has a phone number now.  I can call it from ANYWHERE (even a],
  [26], [Cloudflare], [3,158], [Moltworker is a middleware Worker and adapted scripts that allows runn],
  [27], [luccasveg], [3,116], [🦀 Introducing Crabwalk 🦀  Open-source companion monitor for Clawdbot.],
  [28], [ericw ai], [2,988], [This guy literally explains everything you need to create top-tier lan],
  [29], [bloggersarve], [2,951], [Claude Cowork is a literal CHEAT CODE for SEO.  I could take ANY local],
  [30], [NirDiamantAI], [2,926], [Claude Code power users, you’ll want to see this.  There’s a public re],
  [31], [itsPaulAi], [2,866], [That's just insane  Kimi K2.5 (which is 100 open source) is as good as],
  [32], [AlexFinn], [2,852], [CRITICAL: EVERYONE USING CLAWDBOT SHOULD RUN THIS PROMPT RIGHT NOW:  B],
  [33], [altryne], [2,666], [Fuck it, moltbot tips and tricks thread, stream of consciousness style],
  [34], [UnslothAI], [2,617], [You can now run Kimi K2.5 locally! 🔥  We shrank the 1T model to 240GB],
  [35], [AlexFinn], [2,545], [I'm returning my Mac Mini  In its place I bought a 10k Mac Studio (+ e],
  [36], [DanielMiessl], [2,518], [As a Security / 98 AI YOLO Maximalist with Guardrails guy, I'm asking],
  [37], [moltbot], [2,470], [🦞Clawdbot 2026.1.23  🎤/TTS goes core  ❤️‍🔥Controllable heartbeats 🔧 /t],
  [38], [yulintwt], [2,467], [This guy literally leaks how to prompt for Claude https://t.co/DqtMZxM],
  [39], [garrytan], [2,449], [I don't know why this isn't just in Claude Code's system prompt https:],
  [40], [opennote], [2,418], [Introducing Feynman-3.   A thinking partner that researches, edits, an],
  [41], [andrarchy], [2,417], [Holy crap. qmd by tobi saved me 96 on tokens with clawdbot. Here's how],
  [42], [geminicli], [2,149], [This video was created entirely within Gemini CLI...  ... in under 10],
  [43], [browomo], [2,144], [Someone asked in a Discord if Clawdbot can actually make money. Not sa],
  [44], [gucaslelfond], [2,064], [snowstorm hack, zerobrew is a drop-in brew replacement. borrowing prin],
  [45], [iruletheworl], [1,960], [morning chat, hope you're ready for a huge week.   gpt 5.3 sonnet 4.7],
  [46], [SimonasDip], [1,905], [it has never been easier to clone a viral video  - grab the URL - past],
  [47], [kuberdenis], [1,899], [business idea: make an agent that checks for newly registered google m],
  [48], [MiniMax AI], [1,818], [MiniMax Agent = Claude cowork + Clawdbot - Lives on your computer AND],
  [49], [rronak], [1,779], [I don't think people have realized how crazy the results are from this],
  [50], [AlexFinn], [1,718], [Every night ClawdBot builds me out new apps and ships more code withou],
  [51], [damianplayer], [1,663], [start an AI ads agency while everyone’s confused.  study the formula.],
  [52], [mattshumer], [1,639], [This demo is the craziest thing you’ll see today. Full stop.  Watch Cl],
  [53], [dr cintas], [1,527], [HUGE NEWS: Ollama just dropped “ollama launch” 🤯  You can now set up a],
  [54], [venturetwins], [1,470], [Reminder: X is a bubble when it comes to AI.  If you spend a lot of ti],
  [55], [oliviscusAI], [1,464], [Tencent just killed fine-tuning and RL with a 18 budget 🤯  They develo],
  [56], [lennysan], [1,369], [Most under-hyped AI tools: 1. WisprFlow (10 mentions) 2. Conductor bui],
  [57], [JaidCodes], [1,363], [Microsoft Trellis https://t.co/Id5PmuTRsc],
  [58], [rahulgs], [1,361], [we built our own background coding agent at ramp: it's called inspect],
  [59], [aibymatt], [1,359], [This guy literally breaks down how to make 3M/year solo with AI from a],
  [60], [TheAhmadOsma], [1,342], [nobody should use ollama btw  gt; slower than llama.cpp on windows gt;],
  [61], [GanimCorey], [1,274], [This is how I onboard a new AI employee (using moltbot)  Every new hir],
  [62], [e opore], [1,254], [Full Stack Folder Structure.  Grab the Modern Full Stack Latest Editio],
  [63], [bearlyai], [1,182], [Claude previously released a Financial Analysis Solution spreadsheet p],
  [64], [ctatedev], [1,128], [agent-browser 0.8.3 is even faster  npm install -g agent-browser https],
  [65], [oliviscusAI], [1,042], [JSON is Dead 🤯  A new format called TOON is going viral for its abilit],
  [66], [aiedge], [1,014], [This is insane.  This Moltbot skill cuts token usage by 95+  https://],
  [67], [AIFrontliner], [988], [BREAKING: ClawdBot can now create winning Ads in minutes.  No need to],
  [68], [boringmarket], [984], [if Claude Code isn't managing your Adwords campaigns with direct acces],
  [69], [andrarchy], [970], [This clawdbot https://t.co/forMg0nqeP can cut down token consumption 9],
  [70], [DhravyaShah], [968], [https://t.co/CyBO5MRmJE],
  [71], [petergostev], [952], [According to The Information, ChatGPT ads are being priced at 60 per 1],
  [72], [bored2boar], [943], [Leaked 40M in Polymarket arbitrage money.  Combinatorial arb, rebalanc],
  [73], [chrispisarsk], [922], [I asked Clawdbot to do sales and find prospects + get meetings  It boo],
  [74], [aidenybai], [908], [Introducing Ami Browser  Build a feature → Agent tests web app and fix],
  [75], [signulll], [900], [here is a good way to think about jobs to be eliminated by ai:  - if t],
  [76], [firecrawl], [883], [Introducing the Firecrawl Skill + CLI for Agents 🔥  Agents like Claude],
  [77], [shawn pana], [867], [using agent-browser by vercel with browser use is blowing my mind  onl],
  [78], [eptwts], [864], [you can make an insane amount of money by simply monitoring X for AI t],
  [79], [supermemory], [816], [Your moltbot now has infinite memory.   Introducing our new plugin for],
  [80], [erichustls], [766], [If I were afraid of losing my job to AI  had 6 months to save myself,],
  [81], [MattPRD], [765], [Things in AI are moving SO FAST, and it is SO FUN.  If you're staying],
  [82], [GSkrovina], [741], [This is the best article I've read so far this year.    You should rea],
  [83], [hayesdev], [727], [This guy literally created an agent to replace all his employees https],
  [84], [eliebakouch], [688], [Kimi K2.5 is NOT just a small iteration on top of k2, it's now have fu],
  [85], [burakeregar], [683], [my security / vibe coding related posts reached 2M impressions. so i h],
  [86], [browomo], [658], [Your brain is your biggest limitation. I realized this today when I fo],
  [87], [rahulsood], [653], [https://t.co/FPCplTH3eh],
  [88], [TheIshanGosw], [652], [fyi: exa mcp (web search mcp) is completely free],
  [89], [GanimCorey], [631], [https://t.co/yZajMm1SaS],
  [90], [RohunJauhar], [627], [tonight i did something wild  i told my ai to watch a youtube video, l],
  [91], [tom doerr], [620], [Crawls websites into data for LLMs  https://t.co/qWUmYsVfHy https://t.],
  [92], [aiedge], [619], [https://t.co/Qz6pqfMrsq],
  [93], [DhravyaShah], [600], [you guys have been waiting for this...  Supermemory for Clawd bot!   G],
  [94], [notnotstorm], [591], [how to get your agents to follow rust best practices:  enforce pedanti],
  [95], [david attisa], [588], [https://t.co/1O4qv3cq1P],
  [96], [superagent], [571], [We are Superagent, the AI product for deeper thinking.  Now part of Ai],
  [97], [corbin braun], [569], [moltbot has no real use case for most people.  in reality, if you have],
  [98], [PrestonPysh], [526], [This is a worthy read.  Especially if you want to understand why clawd],
  [99], [boringmarket], [523], [how to structure high converting email sequences (copy this / give it],
  [100], [mattshumer], [521], [Probably the single most useful thing you can install on your Clawdbot],
  [101], [doodlestein], [517], [Agent coding life hack:  I’m 100 convinced that there are hundreds of],
  [102], [wildmindai], [516], [Not a Qwen-TTS, but the small and fast LuxTTS delivers SOTA voice clon],
  [103], [francedot], [515], [https://t.co/szWUllU6No],
  [104], [rudrank], [480], [App Store Connect CLI 0.16.0 is out as one of the biggest releases yet],
  [105], [ZhentingQi], [472], [Agent scaffolding matters as much as, or even more than, raw model cap],
  [106], [JosephKChoi], [449], [just found a guy doing real human UGC but paying per view like it's cl],
  [107], [bored2boar], [448], [This algorithm is the key for any basic Polymarket arbitrage bot.  Bui],
  [108], [bqbrady], [448], [Closing the Software Loop  I've become convinced that it is possible t],
  [109], [morganlinton], [424], [ClawdBot is amazing - it absolutely deserves all the attention it’s ge],
  [110], [mreflow], [415], [I love this take.],
  [111], [ghoshal], [396], [Calling it now.  People who know what they're doing on training clawdb],
  [112], [JulianGoldie], [386], [Google + China just released 2 free AI models that replace 500/month t],
  [113], [WorkflowWhis], [341], [everyone's sleeping on boring industries for automation.  while tech b],
  [114], [arscontexta], [336], [claude code + obsidian as infrastructure for agents to think in  not j],
  [115], [WorkflowWhis], [326], [https://t.co/aVUfLCCmUl],
  [116], [david attisa], [325], [what is this sorcery?  https://t.co/aELoQT5T1s  those prompts on https],
  [117], [kieranklaass], [305], [soon, Claude Code swarm orchestration has 4 core patterns:  1. Paralle],
  [118], [0xSammy], [263], [If you’re going to read any article this week, read this  It opens you],
  [119], [morganlinton], [252], [I think we’re going to be talking about this Cua + ClawdBot combo a lo],
  [120], [ankitkr0], [244], [Introducing ProbablyProfit, a framework for anyone to build Polymarket],
  [121], [pipelineabus], [237], [this is actually insane sauce lol...  with people literally hacking in],
  [122], [adisingh], [219], [I just gave my Clawdbot its own inbox using agentmail   No risk of pro],
  [123], [emilylambert], [216], [Remotion now has Agent Skills that allow you to make videos just with],
  [124], [mattshumer], [203], [Clawdbot with AgentMail is as good as a real executive assistant.  Bey],
  [125], [yulintwt], [197], [This guy literally shows how to make ChatGPT 10x more accurate https:/],
  [126], [vgnsh], [194], [We’re open-sourcing some of moltbot's formal security models: small, p],
  [127], [DanielMiessl], [174], [Hey all, heads up on the https://t.co/vwDam8mAsF stuff, which is an AW],
  [128], [localghost], [173], [Clawdbot now takes an idea, manages codex and claude, debates them on],
  [129], [ashen one], [157], [It's been exactly one day with Clawdbot (Midir), here are the 8 Jobs I],
  [130], [damianplayer], [150], [there’s MILLIONS in free alpha sitting in businesses run by people who],
  [131], [yoheinakajim], [129], [langchain, babyagi, autogpt, autogen, crew ai, claude code, devin, ral],
  [132], [gmickel], [124], [How it started → How it's going  From single-worker Ralph Mode to para],
  [133], [PrajwalTomar], [102], [Okay, this is insane.  I tagged Lovable inside ChatGPT and it one shot],
  [134], [liu8in], [101], [if you are playing with HeyGen + Remotion —gt;  you don’t want to miss],
  [135], [twannl], [83], [philippberner PaulSolt I would love contributions! I wrote a pretty cl],
  [136], [0xPaulius], [79], [POV ralphing on a clean UI on getkomand  let it cook for 24hr+ direct],
  [137], [yulintwt], [78], [This guy literally shows how to get better results from Claude Code in],
  [138], [morganlinton], [73], [I feel like this page on the Cloudflare site deserves to be getting a],
  [139], [Rames Jusso], [66], [Claude Code + Remotion + HeyGen is next level  We built this skill in],
  [140], [mamagnus00], [64], [25 of browser agents fail. not because the LLM is dumb, but because cl],
  [141], [AndrewCurran], [51], [eliebakouch Thinking is now multimodal, I just tested it https://t.co/],
  [142], [surim0n], [48], [quick tips for managing clawdbot token usage  context  - use /new with],
  [143], [theplgeek], [42], [Just released ralph-tui v0.6.0  bun install -g ralph-tui  Feat: Custom],
)

#pagebreak()

= Key Insights and Actions

#table(
  columns: (auto, 1fr, 1fr),
  inset: 4pt,
  fill: (col, row) => if row == 0 { rgb("#4a6a7c") } else if calc.rem(row, 2) == 0 { rgb("#f0f4f7") } else { white },
  text(fill: white, weight: "bold", size: 7pt)[Source],
  text(fill: white, weight: "bold", size: 7pt)[Insight],
  text(fill: white, weight: "bold", size: 7pt)[Action],
  [karpathy], [Agent-first coding is normal now], [Keep Clawdbot workflow],
  [karpathy], [Give success criteria not instructions], [Update prompts],
  [Kimi], [K2.5 open-source visual agent], [Test for visual tasks],
  [geerlingguy], [Open-source TTS killed ElevenLabs], [We have Qwen3-TTS],
  [OpenAI], [Ads coming to ChatGPT], [May degrade free tier],
  [aiedge], [QMD skill cuts 95 percent tokens], [HIGH PRIORITY test],
  [AlexFinn], [Clawdbot memory config tip], [Verify our config],
)

= Action Items

#box(fill: rgb("#fff0f0"), inset: 6pt, radius: 3pt, width: 100%)[
HIGH: Test QMD skill - Read Dario essay - Verify memory config
]

#align(center)[#text(size: 7pt, fill: gray)[123 bookmarks - Bird CLI - Jan 29 2026]]
