#!/bin/bash
#
# Payroll Pipeline - Full Automation
#
# Runs the complete payroll workflow:
# 1. Export timesheets from 7shifts
# 2. Validate and check for issues
# 3. Import to QuickBooks
# 4. Generate exception report
#
# Usage:
#   ./payroll-pipeline.sh                    # Last 2 weeks
#   ./payroll-pipeline.sh 2026-01-01 2026-01-15  # Custom dates
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DATA_DIR="$PROJECT_DIR/data/7shifts"
LOG_DIR="$PROJECT_DIR/logs"

# Create directories if needed
mkdir -p "$DATA_DIR" "$LOG_DIR"

# Date handling
if [ -n "$1" ] && [ -n "$2" ]; then
    START_DATE="$1"
    END_DATE="$2"
else
    # Default to last 2 weeks
    END_DATE=$(date +%Y-%m-%d)
    START_DATE=$(date -v-14d +%Y-%m-%d 2>/dev/null || date -d "14 days ago" +%Y-%m-%d)
fi

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="$LOG_DIR/payroll_${TIMESTAMP}.log"

echo "============================================" | tee "$LOG_FILE"
echo "  PAYROLL PIPELINE - $(date)" | tee -a "$LOG_FILE"
echo "  Period: $START_DATE to $END_DATE" | tee -a "$LOG_FILE"
echo "============================================" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"

# Step 1: Export from 7shifts
echo "📊 Step 1: Exporting from 7shifts..." | tee -a "$LOG_FILE"
cd "$SCRIPT_DIR"

if ! node 7shifts-export.js --start "$START_DATE" --end "$END_DATE" 2>&1 | tee -a "$LOG_FILE"; then
    echo "❌ 7shifts export failed!" | tee -a "$LOG_FILE"
    exit 1
fi

# Find the output file
TIMESHEET_FILE="$DATA_DIR/timesheets_${START_DATE}_to_${END_DATE}.json"
if [ ! -f "$TIMESHEET_FILE" ]; then
    echo "❌ Timesheet file not found: $TIMESHEET_FILE" | tee -a "$LOG_FILE"
    exit 1
fi

echo "" | tee -a "$LOG_FILE"

# Step 2: Validation
echo "🔍 Step 2: Validating timesheet data..." | tee -a "$LOG_FILE"

# Check for open punches
OPEN_COUNT=$(jq '.open_punches' "$TIMESHEET_FILE")
if [ "$OPEN_COUNT" -gt 0 ]; then
    echo "⚠️  Warning: $OPEN_COUNT open punches found!" | tee -a "$LOG_FILE"
    echo "   These employees are missing clock-out times:" | tee -a "$LOG_FILE"
    jq -r '.data[] | select(.status == "open") | "   - \(.employee_name) on \(.date)"' "$TIMESHEET_FILE" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    
    # Prompt for confirmation
    read -p "Continue with import? (y/n): " CONFIRM
    if [ "$CONFIRM" != "y" ]; then
        echo "Aborted by user." | tee -a "$LOG_FILE"
        exit 0
    fi
fi

# Check for unusual hours
echo "   Checking for unusual hours..." | tee -a "$LOG_FILE"
jq -r '.data[] | select(.hours_worked != "OPEN") | select((.hours_worked | tonumber) > 12) | "   ⚠️  \(.employee_name): \(.hours_worked) hours on \(.date)"' "$TIMESHEET_FILE" | tee -a "$LOG_FILE"

echo "" | tee -a "$LOG_FILE"

# Step 3: Import to QuickBooks
echo "📥 Step 3: Importing to QuickBooks..." | tee -a "$LOG_FILE"

if ! node quickbooks-import.js --file "$TIMESHEET_FILE" 2>&1 | tee -a "$LOG_FILE"; then
    echo "❌ QuickBooks import failed!" | tee -a "$LOG_FILE"
    exit 1
fi

echo "" | tee -a "$LOG_FILE"

# Step 4: Generate summary report
echo "📝 Step 4: Generating summary report..." | tee -a "$LOG_FILE"

REPORT_FILE="$PROJECT_DIR/analysis/payroll_report_${START_DATE}_to_${END_DATE}.md"
mkdir -p "$(dirname "$REPORT_FILE")"

cat > "$REPORT_FILE" << EOF
# Payroll Report

**Period:** $START_DATE to $END_DATE
**Generated:** $(date)

## Summary

$(jq -r '
"- **Total Time Punches:** \(.total_punches)
- **Open Punches:** \(.open_punches)
- **Locations:** \(.locations | length)"
' "$TIMESHEET_FILE")

## Hours by Employee

| Employee | Role | Total Hours |
|----------|------|-------------|
$(jq -r '
.data 
| group_by(.employee_name) 
| map({
    name: .[0].employee_name,
    role: .[0].role,
    hours: [.[] | select(.hours_worked != "OPEN") | .hours_worked | tonumber] | add
  })
| sort_by(-.hours)
| .[]
| "| \(.name) | \(.role) | \(.hours | tostring) |"
' "$TIMESHEET_FILE")

## Exceptions

$(jq -r '
if .open_punches > 0 then
  "### Open Punches\n\(.data[] | select(.status == "open") | "- \(.employee_name) on \(.date)")"
else
  "No exceptions found."
end
' "$TIMESHEET_FILE")

---
*Auto-generated by payroll pipeline*
EOF

echo "   Report saved: $REPORT_FILE" | tee -a "$LOG_FILE"

echo "" | tee -a "$LOG_FILE"
echo "============================================" | tee -a "$LOG_FILE"
echo "  PAYROLL PIPELINE COMPLETE" | tee -a "$LOG_FILE"
echo "  Log: $LOG_FILE" | tee -a "$LOG_FILE"
echo "  Report: $REPORT_FILE" | tee -a "$LOG_FILE"
echo "============================================" | tee -a "$LOG_FILE"
