#set page(paper: "us-letter", margin: 1in)
#set text(font: "Helvetica", size: 11pt)

#align(center)[
  #text(size: 24pt, weight: "bold")[Troy Mineer]
  #v(0.3em)
  #text(size: 14pt, fill: gray)[Research Dossier]
  #v(0.3em)
  #text(size: 10pt)[Cookeville, Tennessee]
  #v(1em)
  #text(size: 9pt, fill: gray)[Compiled: January 25, 2026]
]

#line(length: 100%, stroke: 0.5pt + gray)

#v(1em)

#grid(
  columns: (1fr, 2fr),
  gutter: 1em,
  [
    #align(center)[
      #box(
        width: 120pt,
        height: 120pt,
        fill: rgb("#f0f0f0"),
        stroke: 1pt + gray,
        radius: 5pt,
        align(center + horizon)[
          #text(size: 9pt, fill: gray)[Facebook Profile Photo]
          #v(0.5em)
          #text(size: 8pt, fill: gray)[\@troy.mineer.5]
        ]
      )
    ]
  ],
  [
    #text(weight: "bold", size: 14pt)[Basic Information]
    
    #table(
      columns: (auto, 1fr),
      stroke: none,
      row-gutter: 0.4em,
      [*Full Name:*], [Troy Mineer],
      [*Location:*], [Cookeville, Tennessee],
      [*Age (est.):*], [~24-25 years old (Class of 2018)],
      [*Facebook:*], [facebook.com/troy.mineer.5],
    )
  ]
)

#v(1.5em)

== Sports Background

Troy Mineer was a high school basketball player with records found on Hudl (sports recruiting platform).

#table(
  columns: (1fr, 2fr),
  stroke: 0.5pt + gray,
  inset: 8pt,
  [*Sport*], [Basketball],
  [*Position*], [Shooting Guard (SG)],
  [*Height*], [5'11" (180 cm)],
  [*Weight*], [130 lbs (59 kg)],
  [*Jersey Number*], [\#1],
  [*Team*], ["Splash Zone" - Cookeville, TN (2015)],
  [*Class Year*], [2018],
)

#v(1em)

== Location: Cookeville, Tennessee

Cookeville is a city in Putnam County, Tennessee, situated on the Cumberland Plateau.

#table(
  columns: (1fr, 2fr),
  stroke: 0.5pt + gray,
  inset: 8pt,
  [*Population*], [~35,000],
  [*County*], [Putnam County],
  [*Region*], [Upper Cumberland],
  [*University*], [Tennessee Tech University],
  [*Major Industries*], [Education, Healthcare, Manufacturing],
)

#v(1em)

=== Key Employers in Cookeville
- Tennessee Tech University
- Cookeville Regional Medical Center
- Averitt Express (trucking/logistics)
- Various manufacturing facilities

#v(1.5em)

== Social Media Presence

#table(
  columns: (1fr, 2fr, 1fr),
  stroke: 0.5pt + gray,
  inset: 8pt,
  [*Platform*], [*Profile*], [*Status*],
  [Facebook], [facebook.com/troy.mineer.5], [Verified ✓],
  [LinkedIn], [Not found], [—],
  [Twitter/X], [Not found], [—],
  [Instagram], [Not found], [—],
)

#v(1.5em)

== Research Notes

=== What Was Found
- Facebook profile with profile photo
- High school basketball records via Hudl
- Basic geographic/demographic context

=== What Was Not Found
- Current employment/occupation
- LinkedIn professional profile
- Business ownership records
- News articles or publications
- Public property records

=== Search Limitations
Several people-search databases (FastPeopleSearch, WhitePages, ZoomInfo) blocked automated queries with CAPTCHAs. LinkedIn searches require authentication.

#v(2em)

#line(length: 100%, stroke: 0.5pt + gray)

#align(center)[
  #text(size: 9pt, fill: gray)[
    This report contains only publicly available information.
    #v(0.3em)
    Generated by Claw Research Team • January 25, 2026
  ]
]
