// Weekly Twitter Insights Template
// Usage: typst compile weekly-insights.typ output.pdf
// Variables: Replace {{WEEK_RANGE}}, {{GENERATED}}, {{TOTAL}}, etc.

#set page(paper: "us-letter", margin: 0.75in)
#set text(font: "Helvetica Neue", size: 10pt)
#set heading(numbering: none)

#align(center)[
  #text(size: 28pt, weight: "bold")[🦞 Weekly Twitter Insights]
  #v(0.3em)
  #text(size: 14pt)[{{WEEK_RANGE}}]
  #v(0.2em)
  #text(size: 10pt, fill: luma(100))[Generated: {{GENERATED}}]
]

#v(1em)
#line(length: 100%)

= 📊 Executive Summary

#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  gutter: 12pt,
  
  box(fill: luma(245), inset: 12pt, radius: 4pt)[
    #align(center)[
      #text(size: 24pt, weight: "bold")[{{TOTAL}}]
      #v(0.2em)
      #text(size: 9pt)[Bookmarks]
    ]
  ],
  
  box(fill: luma(245), inset: 12pt, radius: 4pt)[
    #align(center)[
      #text(size: 24pt, weight: "bold")[{{AUTHORS}}]
      #v(0.2em)
      #text(size: 9pt)[Unique Authors]
    ]
  ],
  
  box(fill: luma(245), inset: 12pt, radius: 4pt)[
    #align(center)[
      #text(size: 24pt, weight: "bold")[{{TOP_THEME}}]
      #v(0.2em)
      #text(size: 9pt)[Top Theme]
    ]
  ],
  
  box(fill: luma(245), inset: 12pt, radius: 4pt)[
    #align(center)[
      #text(size: 24pt, weight: "bold")[{{TOP_AUTHOR}}]
      #v(0.2em)
      #text(size: 9pt)[Top Voice]
    ]
  ],
)

#v(1em)

= 🔥 Trending Topics

#box(fill: rgb("#FFF8E7"), inset: 12pt, radius: 4pt, width: 100%)[
  {{TRENDING_TOPICS}}
]

#v(1em)

= 👤 Top Voices This Week

#table(
  columns: (auto, 1fr, auto),
  inset: 8pt,
  fill: (col, row) => if row == 0 { luma(230) } else { white },
  [*Rank*], [*Author*], [*Bookmarks*],
  {{AUTHOR_ROWS}}
)

#pagebreak()

= 📂 Insights by Theme

{{THEME_SECTIONS}}

#pagebreak()

= ⚡ Key Takeaways & Actions

#box(fill: rgb("#E8F5E9"), inset: 16pt, radius: 4pt, width: 100%)[
  {{TAKEAWAYS}}
]

#v(1em)

= 🎯 Recommended Actions

#box(fill: rgb("#E3F2FD"), inset: 16pt, radius: 4pt, width: 100%)[
  {{ACTIONS}}
]

#line(length: 100%)

#align(center)[
  #text(size: 9pt, fill: luma(100))[
    Generated by Claw 🦞 | Weekly Twitter Intelligence
  ]
]
