#!/usr/bin/env node
/**
 * Morning Report Generator
 * Compiles all research docs into a beautiful PDF
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const RESEARCH_DIR = '/Users/marbagent/clawd/research';
const OUTPUT_DIR = '/Users/marbagent/clawd/reports';
const TEMPLATE = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    
    * { box-sizing: border-box; }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      line-height: 1.6;
      color: #1a1a2e;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      background: #fff;
    }
    
    .cover {
      text-align: center;
      padding: 60px 0;
      border-bottom: 3px solid #6366f1;
      margin-bottom: 40px;
    }
    
    .cover h1 {
      font-size: 2.5em;
      margin: 0;
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    
    .cover .date {
      font-size: 1.2em;
      color: #64748b;
      margin-top: 10px;
    }
    
    .cover .subtitle {
      font-size: 1em;
      color: #94a3b8;
      margin-top: 5px;
    }
    
    .toc {
      background: #f8fafc;
      padding: 20px 30px;
      border-radius: 12px;
      margin-bottom: 40px;
    }
    
    .toc h2 {
      margin-top: 0;
      color: #6366f1;
    }
    
    .toc ul {
      list-style: none;
      padding: 0;
    }
    
    .toc li {
      padding: 8px 0;
      border-bottom: 1px solid #e2e8f0;
    }
    
    .toc li:last-child {
      border-bottom: none;
    }
    
    .toc a {
      color: #334155;
      text-decoration: none;
    }
    
    .section {
      margin-bottom: 50px;
      page-break-inside: avoid;
    }
    
    .section-header {
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      color: white;
      padding: 15px 20px;
      border-radius: 8px 8px 0 0;
      margin-bottom: 0;
    }
    
    .section-content {
      background: #f8fafc;
      padding: 20px;
      border-radius: 0 0 8px 8px;
      border: 1px solid #e2e8f0;
      border-top: none;
    }
    
    h1 { font-size: 1.8em; color: #1e293b; }
    h2 { font-size: 1.4em; color: #6366f1; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
    h3 { font-size: 1.2em; color: #475569; }
    
    code {
      background: #1e293b;
      color: #e2e8f0;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }
    
    pre {
      background: #1e293b;
      color: #e2e8f0;
      padding: 15px;
      border-radius: 8px;
      overflow-x: auto;
    }
    
    pre code {
      background: none;
      padding: 0;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }
    
    th {
      background: #6366f1;
      color: white;
    }
    
    tr:hover {
      background: #f1f5f9;
    }
    
    .highlight-box {
      background: linear-gradient(135deg, #fef3c7, #fde68a);
      border-left: 4px solid #f59e0b;
      padding: 15px;
      border-radius: 0 8px 8px 0;
      margin: 15px 0;
    }
    
    .action-item {
      background: linear-gradient(135deg, #dcfce7, #bbf7d0);
      border-left: 4px solid #22c55e;
      padding: 15px;
      border-radius: 0 8px 8px 0;
      margin: 15px 0;
    }
    
    ul, ol {
      padding-left: 20px;
    }
    
    li {
      margin: 8px 0;
    }
    
    .emoji {
      font-size: 1.2em;
    }
    
    .footer {
      text-align: center;
      padding: 30px;
      color: #94a3b8;
      border-top: 1px solid #e2e8f0;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  {{CONTENT}}
  <div class="footer">
    Generated by Claw 🐾 • {{DATE}}
  </div>
</body>
</html>
`;

async function generateReport() {
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Get all markdown files
  const files = fs.readdirSync(RESEARCH_DIR)
    .filter(f => f.endsWith('.md'))
    .sort();

  if (files.length === 0) {
    console.error('No research files found!');
    process.exit(1);
  }

  console.log(`Found ${files.length} research files`);

  // Build table of contents
  const toc = files.map((f, i) => {
    const name = f.replace('.md', '').replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    return `<li><span class="emoji">📄</span> ${i + 1}. ${name}</li>`;
  }).join('\n');

  // Build sections
  const sections = files.map((f, i) => {
    const content = fs.readFileSync(path.join(RESEARCH_DIR, f), 'utf-8');
    const name = f.replace('.md', '').replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    
    // Convert markdown to HTML (basic conversion)
    let html = content
      // Headers
      .replace(/^### (.*$)/gm, '<h3>$1</h3>')
      .replace(/^## (.*$)/gm, '<h2>$1</h2>')
      .replace(/^# (.*$)/gm, '<h1>$1</h1>')
      // Bold and italic
      .replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      // Code blocks
      .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // Lists
      .replace(/^\s*[-*]\s+(.*)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
      // Numbered lists  
      .replace(/^\d+\.\s+(.*)$/gm, '<li>$1</li>')
      // Links
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
      // Paragraphs
      .replace(/\n\n/g, '</p><p>')
      // Highlight boxes for key findings
      .replace(/<p><strong>Key (.*?):<\/strong>/gi, '<div class="highlight-box"><strong>Key $1:</strong>')
      .replace(/<p><strong>Recommendation.*?:<\/strong>/gi, '<div class="action-item"><strong>Recommendation:</strong>');

    return `
      <div class="section">
        <div class="section-header">
          <h2 style="margin:0;color:white;">📌 ${i + 1}. ${name}</h2>
        </div>
        <div class="section-content">
          ${html}
        </div>
      </div>
    `;
  }).join('\n');

  // Build cover
  const date = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'America/Denver'
  });

  const cover = `
    <div class="cover">
      <h1>🌅 Morning Research Report</h1>
      <div class="date">${date}</div>
      <div class="subtitle">${files.length} Deep-Dive Research Documents</div>
    </div>
    <div class="toc">
      <h2>📑 Table of Contents</h2>
      <ul>${toc}</ul>
    </div>
  `;

  // Assemble final HTML
  const html = TEMPLATE
    .replace('{{CONTENT}}', cover + sections)
    .replace('{{DATE}}', date);

  // Write HTML
  const htmlPath = path.join(OUTPUT_DIR, 'morning-report.html');
  fs.writeFileSync(htmlPath, html);
  console.log(`HTML saved to ${htmlPath}`);

  // Generate PDF using Puppeteer
  try {
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    const pdfPath = path.join(OUTPUT_DIR, `morning-report-${new Date().toISOString().split('T')[0]}.pdf`);
    await page.pdf({
      path: pdfPath,
      format: 'A4',
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
      printBackground: true
    });
    
    await browser.close();
    console.log(`PDF saved to ${pdfPath}`);
    return pdfPath;
  } catch (err) {
    console.error('Puppeteer PDF failed, trying pandoc...', err.message);
    
    // Fallback to pandoc
    const mdPath = path.join(OUTPUT_DIR, 'morning-report.md');
    const combinedMd = files.map(f => {
      const content = fs.readFileSync(path.join(RESEARCH_DIR, f), 'utf-8');
      const name = f.replace('.md', '').replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      return `# ${name}\n\n${content}\n\n---\n\n`;
    }).join('');
    
    fs.writeFileSync(mdPath, `# Morning Research Report\n\n${date}\n\n---\n\n${combinedMd}`);
    
    const pdfPath = path.join(OUTPUT_DIR, `morning-report-${new Date().toISOString().split('T')[0]}.pdf`);
    execSync(`pandoc "${mdPath}" -o "${pdfPath}" --pdf-engine=wkhtmltopdf 2>/dev/null || pandoc "${mdPath}" -o "${pdfPath}" 2>/dev/null`);
    console.log(`PDF saved to ${pdfPath}`);
    return pdfPath;
  }
}

generateReport().then(pdfPath => {
  console.log('Report generation complete!');
  console.log('PDF:', pdfPath);
}).catch(err => {
  console.error('Error generating report:', err);
  process.exit(1);
});
